# Generated by Django 3.0.5 on 2020-04-08 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('tags', models.CharField(max_length=200, verbose_name='tags')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='url')),
                ('products', models.IntegerField(default=0, null=True, verbose_name='products')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('ingredients', models.TextField(blank=True, null=True, verbose_name='ingredients')),
                ('store', models.TextField(blank=True, null=True, verbose_name='store')),
                ('nutrition_grade', models.CharField(choices=[('', 'N/A'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], default='', max_length=1, null=True)),
                ('code', models.IntegerField(default=0, verbose_name='code')),
                ('url', models.TextField(blank=True, null=True, verbose_name='url')),
                ('img_url', models.TextField(blank=True, null=True, verbose_name='image_url')),
                ('fat_100', models.FloatField(blank=True, default=0, null=True, verbose_name='fat_100g')),
                ('fat_lvl', models.CharField(blank=True, max_length=10, null=True, verbose_name='fat_lvl')),
                ('saturated_fat_100', models.FloatField(blank=True, default=0, null=True, verbose_name='saturated_fat_100g')),
                ('saturated_fat_lvl', models.CharField(blank=True, max_length=10, null=True, verbose_name='saturated_fat_lvl')),
                ('sugar_100', models.FloatField(blank=True, default=0, null=True, verbose_name='sugar_100g')),
                ('sugar_lvl', models.CharField(blank=True, max_length=10, null=True, verbose_name='sugar_lvl')),
                ('salt_100', models.FloatField(blank=True, default=0, null=True, verbose_name='salt_100g')),
                ('salt_lvl', models.CharField(blank=True, max_length=10, null=True, verbose_name='salt_lvl')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='purebeurre.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_category', to='purebeurre.Category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='purebeurre.Product')),
                ('substitute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='purebeurre.Product')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
