# Generated by Django 3.0.5 on 2020-05-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purebeurre', '0002_auto_20200502_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='category',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='product',
        ),
    ]
