# Generated by Django 3.0.5 on 2020-05-31 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import purebeurre.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('purebeurre', '0003_auto_20200503_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfos',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(upload_to=purebeurre.models.photo_path)),
            ],
        ),
    ]
